name: flutter_table_plus
description: "A highly customizable and efficient table widget for Flutter, featuring synchronized scrolling, theming, sorting, selection, column reordering, hover buttons, and expandable rows."
version: 2.15.0
homepage: https://github.com/kihyun1998/flutter_table_plus
repository: https://github.com/kihyun1998/flutter_table_plus
topics:
  - table
  - datatable
  - data-table
  - grid
  - datagrid

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.10.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_checkbox: ^0.2.1
  just_tooltip: ^0.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  fake_async: ^1.3.1
  benchmark_harness: ^2.3.1

flutter:
