import 'dart:math';

import 'employee.dart';

/// Utility class for generating random employee data for testing
/// Supports generating 10 to 100,000+ records efficiently
class RandomDataGenerator {
  /// Seeded per call, from [generateEmployees]'s `startId`.
  ///
  /// **The same arguments give the same people, every time and in every
  /// process.** It used to be one unseeded `Random` shared by every call, and
  /// the Device Wall is what made that a defect rather than a detail: the wall
  /// builds its stage once per frame, so a recipe that generates its rows in
  /// `State` — seven of the eleven do — handed each of the three columns a
  /// different twenty people. Every column then differed by data *and* by
  /// width, and a view whose whole purpose is showing what changed between two
  /// widths could show nothing.
  ///
  /// Fixed here rather than in the wall or in the seven recipes, because this
  /// is the only layer that can be right: the wall is handed an opaque builder
  /// and cannot reach into a recipe's state, and fixing seven recipes fixes
  /// seven recipes. What the wall actually needs is that **building a
  /// destination twice yields the same thing**, and that is a property of where
  /// the data is made.
  ///
  /// Two consequences worth knowing. A bug report can now name a row: two
  /// people at the same preset see the same table, which is the property the
  /// playground's named presets already assume. And `startId` is the knob that
  /// varies the data on purpose — the default keeps a prefix stable, so raising
  /// the row count from 24 to 200 leaves the first 24 people where they were
  /// instead of reshuffling the table under the reader.
  static Random _randomFor(int startId) => Random(startId);

  // Sample data pools for realistic random generation
  static const List<String> _firstNames = [
    'James',
    'Mary',
    'John',
    'Patricia',
    'Robert',
    'Jennifer',
    'Michael',
    'Linda',
    'William',
    'Elizabeth',
    'David',
    'Barbara',
    'Richard',
    'Susan',
    'Joseph',
    'Jessica',
    'Thomas',
    'Sarah',
    'Charles',
    'Karen',
    'Christopher',
    'Nancy',
    'Daniel',
    'Lisa',
    'Matthew',
    'Betty',
    'Anthony',
    'Margaret',
    'Mark',
    'Sandra',
    'Donald',
    'Ashley',
    'Steven',
    'Kimberly',
    'Paul',
    'Emily',
    'Andrew',
    'Donna',
    'Joshua',
    'Michelle',
    'Kenneth',
    'Dorothy',
    'Kevin',
    'Carol',
    'Brian',
    'Amanda',
    'George',
    'Melissa',
    'Edward',
    'Deborah',
    'Ronald',
    'Stephanie',
    'Timothy',
    'Rebecca',
    'Jason',
    'Sharon',
    'Jeffrey',
    'Laura',
    'Ryan',
    'Cynthia',
    'Jacob',
    'Kathleen',
    'Gary',
    'Amy',
    'Nicholas',
    'Shirley',
    'Eric',
    'Angela',
    'Jonathan',
    'Helen',
    'Stephen',
    'Anna',
    'Larry',
    'Brenda',
    'Justin',
    'Pamela',
    'Scott',
    'Nicole',
    'Brandon',
    'Emma',
    'Benjamin',
    'Samantha',
    'Samuel',
    'Katherine',
    'Raymond',
    'Christine',
    'Gregory',
    'Debra',
    'Frank',
    'Rachel',
    'Alexander',
    'Catherine',
    'Patrick',
    'Carolyn',
    'Raymond',
    'Janet',
    'Jack',
    'Ruth',
    'Dennis',
    'Maria',
    'Jerry',
    'Heather',
    'Tyler',
    'Diane',
    'Aaron',
    'Virginia',
    'Jose',
    'Julie',
    'Adam',
    'Joyce',
    'Nathan',
    'Victoria',
    'Henry',
    'Olivia',
    'Douglas',
    'Kelly',
    'Zachary',
    'Christina',
    'Peter',
    'Lauren',
    'Kyle',
    'Joan',
    'Walter',
    'Evelyn',
    'Ethan',
    'Judith',
    'Jeremy',
    'Megan',
    'Harold',
    'Cheryl',
    'Keith',
    'Andrea',
    'Christian',
    'Hannah',
    'Roger',
    'Jacqueline',
    'Noah',
    'Martha',
    'Gerald',
    'Gloria',
    'Carl',
    'Teresa',
    'Terry',
    'Ann',
    'Sean',
    'Sara',
    'Austin',
    'Madison',
    'Arthur',
    'Frances',
    'Lawrence',
    'Kathryn',
    'Jesse',
    'Janice',
    'Dylan',
    'Jean',
    'Bryan',
    'Abigail',
    'Joe',
    'Alice',
  ];

  static const List<String> _lastNames = [
    'Smith',
    'Johnson',
    'Williams',
    'Brown',
    'Jones',
    'Garcia',
    'Miller',
    'Davis',
    'Rodriguez',
    'Martinez',
    'Hernandez',
    'Lopez',
    'Gonzalez',
    'Wilson',
    'Anderson',
    'Thomas',
    'Taylor',
    'Moore',
    'Jackson',
    'Martin',
    'Lee',
    'Perez',
    'Thompson',
    'White',
    'Harris',
    'Sanchez',
    'Clark',
    'Ramirez',
    'Lewis',
    'Robinson',
    'Walker',
    'Young',
    'Allen',
    'King',
    'Wright',
    'Scott',
    'Torres',
    'Nguyen',
    'Hill',
    'Flores',
    'Green',
    'Adams',
    'Nelson',
    'Baker',
    'Hall',
    'Rivera',
    'Campbell',
    'Mitchell',
    'Carter',
    'Roberts',
    'Gomez',
    'Phillips',
    'Evans',
    'Turner',
    'Diaz',
    'Parker',
    'Cruz',
    'Edwards',
    'Collins',
    'Reyes',
    'Stewart',
    'Morris',
    'Morales',
    'Murphy',
    'Cook',
    'Rogers',
    'Gutierrez',
    'Ortiz',
    'Morgan',
    'Cooper',
    'Peterson',
    'Bailey',
    'Reed',
    'Kelly',
    'Howard',
    'Ramos',
    'Kim',
    'Cox',
    'Ward',
    'Richardson',
    'Watson',
    'Brooks',
    'Chavez',
    'Wood',
    'James',
    'Bennett',
    'Gray',
    'Mendoza',
    'Ruiz',
    'Hughes',
    'Price',
    'Alvarez',
    'Castillo',
    'Sanders',
    'Patel',
    'Myers',
    'Long',
    'Ross',
    'Foster',
    'Jimenez',
    'Powell',
    'Jenkins',
    'Perry',
    'Russell',
    'Sullivan',
    'Bell',
    'Coleman',
    'Butler',
    'Henderson',
    'Barnes',
    'Gonzales',
    'Fisher',
    'Vasquez',
    'Simmons',
    'Romero',
    'Jordan',
    'Patterson',
    'Alexander',
    'Hamilton',
    'Graham',
    'Reynolds',
    'Griffin',
    'Wallace',
    'Moreno',
    'West',
    'Cole',
    'Hayes',
    'Bryant',
    'Herrera',
    'Gibson',
    'Ellis',
    'Tran',
    'Medina',
    'Aguilar',
    'Stevens',
    'Murray',
    'Ford',
    'Castro',
    'Marshall',
    'Owens',
    'Harrison',
    'Fernandez',
    'McDonald',
    'Woods',
    'Washington',
    'Kennedy',
    'Wells',
    'Vargas',
    'Henry',
    'Chen',
    'Freeman',
    'Webb',
    'Tucker',
    'Guzman',
    'Burns',
    'Crawford',
    'Olson',
    'Simpson',
    'Porter',
    'Hunter',
  ];

  static const List<String> _departments = [
    'Engineering',
    'Design',
    'Marketing',
    'Sales',
    'HR',
    'Finance',
    'Operations',
    'Customer Support',
    'Product',
    'Legal',
  ];

  static const List<String> _positions = [
    'Senior Software Engineer',
    'Software Engineer',
    'Junior Developer',
    'Frontend Developer',
    'Backend Developer',
    'Full Stack Developer',
    'DevOps Engineer',
    'QA Engineer',
    'Data Scientist',
    'Product Manager',
    'UX Designer',
    'UI Designer',
    'Graphic Designer',
    'Marketing Manager',
    'Content Writer',
    'Social Media Manager',
    'Sales Director',
    'Sales Representative',
    'Account Manager',
    'Business Development',
    'HR Manager',
    'HR Specialist',
    'Recruiter',
    'Financial Analyst',
    'Accountant',
    'Operations Manager',
    'Support Specialist',
    'Team Lead',
    'Technical Writer',
    'System Administrator',
  ];

  static const List<String> _avatars = [
    '👨‍💻',
    '👩‍💻',
    '👨‍🎨',
    '👩‍🎨',
    '👨‍💼',
    '👩‍💼',
    '👨‍🔬',
    '👩‍🔬',
    '👨‍🔧',
    '👩‍🔧',
    '👨‍⚕️',
    '👩‍⚕️',
    '👨‍🏫',
    '👩‍🏫',
    '👨‍🚀',
    '👩‍🚀',
    '👨‍✈️',
    '👩‍✈️',
    '👨‍🎤',
    '👩‍🎤',
    '👨‍🍳',
    '👩‍🍳',
    '👨‍🌾',
    '👩‍🌾',
    '👨‍⚖️',
    '👩‍⚖️',
    '👨‍🏭',
    '👩‍🏭',
    '👨‍💻',
    '👩‍💻',
  ];

  /// Generate a list of random [Employee] data
  ///
  /// Parameters:
  /// - [count]: Number of employees to generate (10 to 100,000+)
  /// - [startId]: Starting ID number (default: 1)
  static List<Employee> generateEmployees(int count, {int startId = 1}) {
    final stopwatch = Stopwatch()..start();
    final random = _randomFor(startId);

    final List<Employee> employees = [];

    for (int i = 0; i < count; i++) {
      final id = startId + i;
      final firstName = _firstNames[random.nextInt(_firstNames.length)];
      final lastName = _lastNames[random.nextInt(_lastNames.length)];
      final department = _departments[random.nextInt(_departments.length)];
      final position = _positions[random.nextInt(_positions.length)];
      final avatar = _avatars[random.nextInt(_avatars.length)];

      // Generate salary based on position level
      final baseSalary = position.contains('Senior') ||
              position.contains('Manager') ||
              position.contains('Director')
          ? 80000 + random.nextInt(120000) // 80k - 200k
          : position.contains('Junior')
              ? 45000 + random.nextInt(35000) // 45k - 80k
              : 55000 + random.nextInt(60000); // 55k - 115k

      // Generate performance score (0.5 - 1.0)
      final performance = 0.5 + (random.nextDouble() * 0.5);

      // Generate random join date (last 5 years)
      final now = DateTime.now();
      final daysAgo = random.nextInt(365 * 5);
      final joinDate = now.subtract(Duration(days: daysAgo));

      employees.add(Employee(
        id: 'emp_${id.toString().padLeft(6, '0')}',
        name: '$firstName $lastName',
        position: position,
        department: department,
        salary: baseSalary,
        avatar: avatar,
        performance: double.parse(performance.toStringAsFixed(2)),
        joinDate: joinDate,
        email:
            '${firstName.toLowerCase()}.${lastName.toLowerCase()}@company.com',
        phone: '+1-555-${random.nextInt(9000) + 1000}',
        isActive: random.nextDouble() > 0.2, // ~80% active
      ));
    }

    stopwatch.stop();
    // ignore: avoid_print
    print('✅ Generated $count employees in ${stopwatch.elapsedMilliseconds}ms');

    return employees;
  }
}
